services:
  # 1. Base de datos para el microservicio Users
  users-db:
    image: postgres:16-alpine
    container_name: users-db
    restart: always
    command: postgres -c log_statement=all -c log_duration=on -c log_min_duration_statement=0 -c "log_line_prefix=%m [%p] %u@%d app=%a "
    environment:
      POSTGRES_USER: users_user
      POSTGRES_PASSWORD: users_password
      POSTGRES_DB: users_db
    expose:
      - "5432"
    volumes:
      - users_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users_user -d users_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Base de datos para el microservicio SwipeShare
  swipeshare-db:
    image: postgres:16-alpine
    container_name: swipeshare-db
    restart: always
    command: postgres -c log_statement=all -c log_duration=on -c log_min_duration_statement=0 -c "log_line_prefix=%m [%p] %u@%d app=%a "
    environment:
      POSTGRES_USER: swipeshare_user
      POSTGRES_PASSWORD: swipeshare_password
      POSTGRES_DB: swipeshare_db
    expose:
      - "5432"
    volumes:
      - swipeshare_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swipeshare_user -d swipeshare_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 3. Microservicio Users
  users:
    build: ./users
    container_name: users
    restart: always
    expose:
      - "8081"
    environment:
      SPRING_APPLICATION_NAME: users
      SPRING_DATASOURCE_URL: jdbc:postgresql://users-db:5432/users_db
      SPRING_DATASOURCE_USERNAME: users_user
      SPRING_DATASOURCE_PASSWORD: users_password
    depends_on:
      users-db:
        condition: service_healthy

  # 4. Microservicio SwipeShare
  swipeshare:
    build: ./swipeshare
    container_name: swipeshare
    restart: always
    expose:
      - "8080"
    environment:
      SPRING_APPLICATION_NAME: swipeshare
      SPRING_DATASOURCE_URL: jdbc:postgresql://swipeshare-db:5432/swipeshare_db
      SPRING_DATASOURCE_USERNAME: swipeshare_user
      SPRING_DATASOURCE_PASSWORD: swipeshare_password
    depends_on:
      swipeshare-db:
        condition: service_healthy
      users:
        condition: service_started

  # 5. Reverse Proxy Nginx (ÚNICO punto de entrada expuesto)
  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    restart: always
    ports:
      - "9090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy_headers.conf:/etc/nginx/proxy_headers.conf:ro
    depends_on:
      users:
        condition: service_started
      swipeshare:
        condition: service_started

  # 6. Administrador de BD
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  users_postgres_data:
  swipeshare_postgres_data: