events {}

http {
    resolver 127.0.0.11 valid=10s;

    server {
        listen 80;

        # Microservicio Users (puerto 8081)
        location /api/users {
            proxy_pass http://users:8081;
            include /etc/nginx/proxy_headers.conf;
        }

        # Microservicio SwipeShare (puerto 8080)
        location /swipeshare {
            proxy_pass http://swipeshare:8080;
            include /etc/nginx/proxy_headers.conf;
        }

        location /api/items {
            proxy_pass http://swipeshare:8080;
            include /etc/nginx/proxy_headers.conf;
        }

        location /api/reviews {
            proxy_pass http://swipeshare:8080;
            include /etc/nginx/proxy_headers.conf;
        }

        location /api/public {
            proxy_pass http://swipeshare:8080;
            include /etc/nginx/proxy_headers.conf;
        }

        location = / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}